name: VPC, Ec2, RDS
on:
  workflow_dispatch:
jobs:
  terraform-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.10.3  # 
          
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Configure Git
        run: |
          git config --global user.email "hassan.mirsf@gmail.com"
          git config --global user.name "hassanmirdev"
      
      - name: Terraform Init (Dev)
        run: |
          cd infra/terraform/environments/dev
          terraform init
          #terraform init -backend-config="bucket=${{ secrets.TF_BUCKET_NAME }}" -backend-config="key=dev.tfstate"

      - name: Terraform Apply (Dev)
        run: |
          cd infra/terraform/environments/dev
          terraform apply -auto-approve -var-file="terraform.tfvars"

      # - name: Terraform Init (Stage)
      #   run: |
      #     cd infra/environment/stage
      #     terraform init

      # - name: Terraform Apply (Stage)
      #   run: |
      #     cd terraform/stage
      #     terraform apply -auto-approve -var-file="terraform.tfvars"

      # - name: Terraform Init (Prod)
      #   run: |
      #     cd terraform/prod
      #     terraform init -backend-config="bucket=${{ secrets.TF_BUCKET_NAME }}" -backend-config="key=prod.tfstate"

      # - name: Terraform Apply (Prod)
      #   run: |
      #     cd terraform/prod
      #     terraform apply -auto-approve -var-file="terraform.tfvars"
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      # # Initialize Terraform
      # - name: Initialize Terraform
      #   run: |
      #     rm -rf .terraform
      #     terraform init

      # # Generate Terraform Plan
      # - name: Generate Terraform Plan
      #   run: terraform plan

      # #  run: terraform plan -out=tfplan

      
      # #  # Generate Markdown with Terraform Docs
      # # - name: Generate Markdown with Terraform Docs
      # #   uses: terraform-docs/gh-actions@v1.3.0
      # #   with:
      # #     working-dir: .
      # #     output-file: README.md
      # #     output-method: inject
      # #     git-push: "true"
      # #     git-push-user-name: "hassanmirdev"
      # #     git-push-user-email: "hassan.mirsf@gmail.com"
      # #   env:
      # #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # # Apply the Terraform configuration to AWS
      # - name: Apply Terraform Configuration
      #   run: terraform apply -auto-approve tfplan
